# Generated by Django 5.0.1 on 2024-01-02 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('coffee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coffee_name', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Dessert', 'Dessert'), ('Sancks', 'Sancks')], default='', max_length=100)),
                ('desc', models.TextField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coffee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('coffee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.coffee')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
